common:
  action_dim: 14
  state_dim: 16
  action_chunk_size: 32
  proprio_len: 1
  num_inference_steps: 10
  action_execution_horizon: 16
  action_prediction_type: x_prediction_v_loss
dataset:
  type: robotwin
  dataset_dir: /mnt/pfs/pg4hw0/mobile/qiwei/mobile/starVLA_xpred_v-pred/LiLa-WAM/Datasets
  data_mode: clean
  camera_names:
  - head_camera
  image_size:
  - 320
  - 240
  task_cond_dir: ./data-500-clean-taskcond
  image_aug: false
  future_frame_offset: null
  indices_config:
    state_indices:
    - 0
    camera_indices:
    - 0
    action_indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
model:
  num_registers: 2
  use_task_cond: true
  vision_encoder:
    checkpoint_path: ./dinov3_pretrain
    feat_layers:
    - -12
    - -8
    - -4
    include_cls_register: true
    fusion_mode: concat
    concat:
      proj_type: linear
      pre_norm: true
      out_dim: null
  future_feat:
    enabled: true
    target_layer: -4
    num_decoder_layers: 4
    num_heads: 4
  action_expert:
    depth: 12
    hidden_size: 768
    num_heads: 8
    vlm_adapter_num_queries: 64
    adapter_depth: 4
training:
  batch_size: 128
  time_sampler: logit_normal
  time_mu: 0.0
  time_sigma: 1.0
  learning_rate: 0.0001
  lr_min: 5.0e-05
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.99
  grad_clip_norm: 1.0
  epochs: 15
  grad_accum_steps: 1
  save_interval_epoch: 1
  lambda_future_feat: 0.5
  x_pred_v_loss_eps: 0.05
  use_vel_weight: false
  vel_weight_alpha: 0.2
  vel_weight_sigma: 0.01
inference:
  smooth_actions: true
  smooth_sigma: 1.0
system:
  num_workers: 16
  pin_memory: true
